### ISSUE TITLE
Is recompiling still needed for 64-bit library device?

### ISSUE THREAD

**Issue by daquexian** [hpi-xnor/android-image-classification#2]
Thanks for your great effort.

In README, 

> If you want to use the library on an ARM64 device you have to recompile the BMXNet library as described here, using the correct toolchain.

However, 153704d200a31d61a01afa4bbb1d2136c2f1049f has already added the 64-bit library.

So is recompiling still needed for 64-bit library device?

**Comment by Bartzi** [comment]
Hmm, you are right, we forgot to delete this paragraph from the README. It should work on a armv8 device.

**Comment by daquexian** [comment]
Thanks for your quick reply and the fix in 31ad4d01ca94a7338f8b6e2bd85e15cf58d417b6!
